"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
var relatorios_1 = require("./routes/relatorios");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use("/relatorios", relatorios_1.default);
var PORT = process.env.PORT || 3000;
app.listen(PORT, function () { return console.log("Servidor rodando na porta ".concat(PORT)); });
